### ISSUE TITLE
开启API网关触发器后访问404

### ISSUE THREAD

**Issue by fulus06** [linthan/scf-go-api-proxy#2]
![图片](https://user-images.githubusercontent.com/12890684/86222775-42115f00-bbb9-11ea-9a45-847ddab7c461.png)

https://service-0gqwmax1-1256955938.sh.apigw.tencentcs.com/release/de

这种是什么原因
![图片](https://user-images.githubusercontent.com/12890684/86222821-52293e80-bbb9-11ea-8e98-edb9dd5af874.png)

**Comment by linthan** [comment]
要在golang里面的路由也加上release前缀。  使用自定义域名  就没有这个release的问题。这种情况传过去的path和golang里面路由定义的path匹配不上 .

**Comment by fulus06** [comment]
我的解决方法：
公网：https://service-i8ynzq4j-1256955938.sh.apigw.tencentcs.com/release/de
前缀的问题，我的函数名叫“de”，所以需要在代码里添加“/de”的前缀
![image](https://user-images.githubusercontent.com/12890684/86429052-eeba2080-bd20-11ea-87fd-596fd3a5fcca.png)
只有这个红圈的可以访问。


实验方法：
`

func handleRequest(ctx context.Context, request events.APIGatewayRequest) (events.APIGatewayResponse, error) {
	fmt.Println("request :",request.Path) // 在日志查询中可以看到 /de
	return echoLambda.ProxyWithContext(ctx, request)
}

`
